org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false

## Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
forge_version=21.1.31
forge_version_range=[21.1.31,)
loader_version_range=[1,)
neogradle.subsystems.parchment.minecraftVersion=1.21
neogradle.subsystems.parchment.mappingsVersion=2024.07.28

## Mod Properties
mod_id=enchantmentmachine
mod_name=EnchantmentMachine
mod_license=LGPL-3.0
mod_group_id=de.cheaterpaul.enchantmentmachine
archivesBaseName=EnchantmentMachine
mod_authors=Cheaterpaul, maxanier
mod_description=This mod adds enchantment blocks for extracting, storing and applying enchantments.
mod_credits=
mod_issue_tracker_url=https://github.com/Cheaterpaul/EnchantmentMachine/issues
pack_format_number=18
main_version=1
major_version=1
minor_version=5
modrinth_id=oNqn5GfR
curseforge_id=436934