modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL = "https://github.com/Cheaterpaul/EnchantmentMachine/issues"
license="LGPL-3.0"

[[mods]] #mandatory
modId="enchantmentmachine"
version="${version}"
displayName="Enchantment Machine"
authors = "Cheaterpaul, maxanier"
[[dependencies.enchantmentmachine]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"
