modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="enchantmentmachine" #mandatory
version="${version}" #mandatory
displayName="Enchantment Machine" #mandatory
[[dependencies.enchantmentmachine]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"
