modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL = "https://github.com/Cheaterpaul/EnchantmentMachine/issues"
license="LGPL-3.0"

[[mods]] #mandatory
modId="enchantmentmachine" #mandatory
version="${version}" #mandatory
displayName="Enchantment machine" #mandatory
authors = "Cheaterpaul, maxanier"
[[dependencies.enchantmentmachine]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"
